### ISSUE TITLE
Error instalando Audit Daemon 

### ISSUE THREAD

**Issue by aasanchez** [phenobarbital/debian-bastion#3]
´´´
 Installing Audit Daemon 

installing Debian package acct
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias  
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes NUEVOS:
  acct
0 actualizados, 1 se instalarán, 0 para eliminar y 0 no actualizados.
Necesito descargar 120 kB de archivos.
Se utilizarán 389 kB de espacio de disco adicional después de esta operación.
Des:1 http://ftp.us.debian.org/debian/ wheezy/main acct amd64 6.5.5-1 [120 kB]
Descargados 120 kB en 0seg. (227 kB/s)
Seleccionando el paquete acct previamente no seleccionado.
(Leyendo la base de datos ... 22514 ficheros o directorios instalados actualmente.)
Desempaquetando acct (de .../acct_6.5.5-1_amd64.deb) ...
Procesando disparadores para install-info ...
Procesando disparadores para man-db ...
Configurando acct (6.5.5-1) ...
Turning on process accounting, file set to '/var/log/account/pacct'.
[master b6dfee7] committing changes in /etc after apt run
 Committer: root root@web.gravata.com.ve
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

After doing this, you may fix the identity used for this commit with:

```
git commit --amend --reset-author
```

 12 files changed, 183 insertions(+)
 create mode 100755 cron.daily/acct
 create mode 100755 cron.monthly/acct
 create mode 100644 default/acct
 create mode 100755 init.d/acct
 create mode 120000 rc0.d/K01acct
 create mode 120000 rc1.d/K01acct
 create mode 120000 rc2.d/S02acct
 create mode 120000 rc3.d/S02acct
 create mode 120000 rc4.d/S02acct
 create mode 120000 rc5.d/S02acct
 create mode 120000 rc6.d/K01acct
Turning off process accounting.
[FAIL] Failed. ... failed!
[warn] Process accounting not available on this system. ... (warning).
Turning on process accounting, file set to '/var/account/pacct'.
´´´

**Comment by phenobarbital** [comment]
acct en Debian Wheezy busca el pacct en una ubicación inexistente y falla su instalación, por eso el el hook 90-selinux hay el siguiente snippet de código:

```
service acct stop
mkdir /var/account
sed -i 's/\/var\/log\/account\/pacct/\/var\/account\/pacct/' /etc/init.d/acct
mv /var/log/account/pacct /var/account/
chown -R root.adm /var/account
service acct start
```

Que crea el directorio, ubica correctamente el pacct, aplica propietario y levanta el servicio.

No sé si este "workaround" sea mejor que corregir el init.d del servicio acct.

Otra posibilidad sería instalarlo pero bloqueando su inicio la primera vez, aplicar el cambio del pacct y luego si, levantarlo.

¿Qué opinas?

**Comment by phenobarbital** [comment]
wow!, gracias!
